#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu1
if [ -x "/etc/init.d/spice-vdagent" ] && [ "$1" = remove ]; then
	invoke-rc.d spice-vdagent stop || exit 1
fi
# End automatically added section
# Automatically added by dh_systemd_start/11.1.6ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'spice-vdagentd.target' >/dev/null || true
fi
# End automatically added section
